name: E2E - Playwright

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: "0 8 * * 6"

  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: npx playwright test

      - name: Notify ntfy on failure
        if: ${{ failure() }}
        run: 
          curl -d "CI test failed $(TZ=Europe/Paris date +'%H:%M:%S %d/%m/%Y') Paris" ntfy.sh/florianlatapie_velib;
          curl -d "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" ntfy.sh/florianlatapie_velib

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload screenshots
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: test-results
          path: test-results/
          retention-days: 30